using Vitraux;

namespace Chronometer;

public class ChronometerModelConfiguration : IViewModelConfiguration<ChronometerViewModel>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("test 1.3"),
        ActionRegistrationStrategy = ActionRegistrationStrategy.OnlyOnceAtStart
    };

    public ModelMappingData ConfigureMapping(IModelMapper<ChronometerViewModel> modelMapper)
        => modelMapper
            .MapValue(chronos => chronos.Hours.ToString("D2")).ToElements.ById("hour").ToContent
            .MapValue(chronos => chronos.Minutes.ToString("D2")).ToElements.ById("minute").ToContent
            .MapValue(chronos => chronos.Seconds.ToString("D2")).ToElements.ById("second").ToContent
            .MapValue(chronos => chronos.TenthSeconds.ToString("D1")).ToElements.ById("tenthsecond").ToContent
            .MapValue(chronos => GetStartPauseTitleByRunning(chronos.IsRunning)).ToElements.ById("startPauseButton").ToContent
            .MapActionAsync(chronos => chronos.StartPause()).FromInputs.ById("startPauseButton").On("click")
            .MapValue(chronos => chronos.IsRunning).ToElements.ById("resetButton").ToAttribute("disabled")
            .MapActionAsync(chronos => chronos.Reset()).FromInputs.ById("resetButton").On("click")
            .Data;

    private static string GetStartPauseTitleByRunning(bool isRunning)
        => isRunning ? "Pause" : "Start";
}
