namespace Vitraux.Execution.Tracking;
internal record class EncodedTrackedViewModelAllData(IEnumerable<EncodedTrackedViewModelValueData> ValueProperties, IEnumerable<EncodedTrackedViewModelCollectionData> CollectionProperties);
