namespace Vitraux.Modeling.Building.Contracts.ElementBuilders.Actions;

public interface IRootActionAddParameterNameFinallizableBuilder<TViewModel> : IRootActionAddParameterNameBuilder<TViewModel>, IRootParametrizableActionSourceFinallizableBuilder<TViewModel>
{
}