namespace Vitraux.Execution.Serialization;

internal record class EncodedViewModelSerializationData(IEnumerable<EncodedValueViewModelSerializationData> ValueProperties, IEnumerable<EncodedCollectionViewModelSerializationData> CollectionProperties);
