using PetOwnerWasm.ViewModel;
using Vitraux;

namespace PetOwnerWasm.ModelConfigurations;

internal class AllPetOwnerNamesConfiguration : IViewModelConfiguration<AllPetOwnerNames>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("1.0")
    };

    public ModelMappingData ConfigureMapping(IModelMapper<AllPetOwnerNames> modelMapper)
        => modelMapper
            .MapActionAsync(apo => apo.AddFakePetOwner()).FromInputs.ById("fake-po-button").On("click")
            .MapActionAsync<SelectPetOwnerBinder>().FromInputs.ById("petowners").On("change").AddParameterValue
            .MapCollection(apo => apo.Names)
                .ToContainerElements.ById("petowners")
                .FromTemplate("petowner-option-template")
                    .MapValue(name => name.Id).ToElements.ByQuery("option").ToAttribute("value")
                    .MapValue(name => name.Name).ToElements.ByQuery("option").ToContent
            .EndCollection
            .Data;
}
