using PetOwnerWasm.ViewModel;
using System.Diagnostics.CodeAnalysis;
using Vitraux;

namespace PetOwnerWasm.ModelConfigurations;

[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]
internal class SelectPetOwnerBinder : ActionParametersBinderAsyncBase<AllPetOwnerNames>
{
    public override Task BindActionAsync(AllPetOwnerNames viewModel, IDictionary<string, IEnumerable<string>> parameters)
        => viewModel.SelectPetOwner(int.Parse(parameters["inputValue"].Single()));
}

internal class AllPetOwnerNamesConfiguration : IModelConfiguration<AllPetOwnerNames>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        VMAutoGeneratedFunctionCaching = VMAutoGeneratedFunctionCaching.ByVersion("1.0")
    };

    public ModelMappingData ConfigureMapping(IModelMapper<AllPetOwnerNames> modelMapper)
        => modelMapper
            .MapActionAsync(apo => apo.AddFakePetOwner()).FromInputs.ById("fake-po-button").On("click")
            .MapActionAsync<SelectPetOwnerBinder>().FromInputs.ById("petowners").On("change").AddParameterValue
            .MapCollection(apo => apo.Names)
                .ToContainerElements.ById("petowners")
                .FromTemplate("petowner-option-template")
                    .MapValue(name => name.Id).ToElements.ByQuery("option").ToAttribute("value")
                    .MapValue(name => name.Name).ToElements.ByQuery("option").ToContent
            .EndCollection
            .Data;
}
