using PetOwnerWasm.ViewModel;
using Vitraux;
using Vitraux.Helpers;

namespace PetOwnerWasm.ModelConfigurations;

public class PetOwnerConfiguration(IDataUriConverter dataUriConverter) : IModelConfiguration<PetOwner>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        VMAutoGeneratedFunctionCaching = VMAutoGeneratedFunctionCaching.ByVersion("test 1.0")
    };

    public ModelMappingData ConfigureMapping(IModelMapper<PetOwner> modelMapper)
        => modelMapper
            .MapValue(po => po.Name)
                .ToElements.ById("petowner-name").ToContent
                .ToJsFunction("poNameFunction").FromModule(new Uri("./modules/po.js", UriKind.Relative))
            .MapValue(po => po.Address).ToElements.ById("petowner-address").ToContent
            .MapValue(po => po.PhoneNumber).ToElements.ById("petowner-phone-number").ToContent
            .MapValue(po => po.Subscription).ToOwnMapping
            .MapValue(po => po.HtmlComments).ToElements.ByQuery(".comments").ToHtml
            .MapCollection(po => po.Pets)
                .ToJsFunction("pets.manage").FromModule(new Uri("./modules/pets.js", UriKind.Relative))
                .ToTables.ById("petowner-pets")
                .PopulatingRows.ToTBody(1).FromTemplate("petowner-pet-row")
                    .MapValue(pet => pet.Name).ToElements.ByQuery("[data-id='pet-name']").ToContent
                    .MapCollection(pet => pet.Vaccines)
                        .ToContainerElements.ByQuery(".vaccines-list")
                        .FromTemplate("vaccine-item-template")
                        .ToOwnMapping
                    .EndCollection
                    .MapValue(pet => ToDataUri(pet.Photo)).ToElements.ByQuery("[data-id='pet-photo']").ToAttribute("src")
                    .MapCollection(pet => pet.Antiparasitics)
                        .ToJsFunction("globalThis.manageAntiparasitics")
                        .ToContainerElements.ByQuery(".antiparasitics-list")
                        .FromTemplate("antiparasitic-item-template")
                            .MapValue(a => a.Name).ToElements.ByQuery(".antiparasitic-name").ToContent
                            .MapValue(a => a.DateApplied).ToElements.ByQuery(".antiparasitic-date").ToContent
                    .EndCollection
            .EndCollection
            .Data;

    private string ToDataUri(byte[] data) => dataUriConverter.ToDataUri(MimeImage.Png, data);
}
