using Vitraux;

namespace FromTemplate;

public class FromTemplateModelConfiguration(IViewUpdater<FromTemplateViewModel> viewUpdater) : IViewModelConfiguration<FromTemplateViewModel>
{
    private IEnumerable<int> numbersToSuffle = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("test FromTemplate"),
        ActionRegistrationStrategy = ActionRegistrationStrategy.OnlyOnceAtStart
    };

    public ModelMappingData ConfigureMapping(IModelMapper<FromTemplateViewModel> modelMapper)
        => modelMapper
            .MapValue(vm => FormatTime(vm.Now))
                .MapValueZeroToZeroCases()
                .MapValueOneOrManyToZeroCases()
                .MapValueOneOrManyToOneOrManyCases()
            .MapCollection(vm => vm.ShuffledNumbers).ToContainerElements.ById("dfdfdsf").FromTemplate("dfsdfdf")
                .MapValue(n=>n.ShuffledNumber).ToElements.ByQuery("dfsdf").ToContent
                .MapCollection(n=>n.Children).ToContainerElements.ByQuery("dfsdfsdf").FromTemplate("dasd")
                    .MapValue(n=>n.ShuffledNumber).ToElements.ByQuery("dfsfdsf").ToContent
                .EndCollection
            .EndCollection
            .MapCollection(vm => vm.ShuffledNumbers)
                .ToContainerElements.ByQuery(".container-level-1").FromTemplate("container-level-1-template")
                    .MapValue(n => n.ShuffledNumber).ToElements.ByQuery("[item-level-1]").ToContent
                    .MapCollection(n => n.Children).ToTables.ByQuery("[table-level-2]").PopulatingRows.FromTemplate("table-level-2-template")
                        .MapValue(c => c.ShuffledNumber).ToElements.ByQuery("[cell-level-2]").ToContent
                        .MapCollection(c => c.Children).ToContainerElements.ByQuery("cell-container-2").FromTemplate("container-level-3-template")
                            .MapValue(c => c.ShuffledNumber).ToElements.ByQuery("item-level-3").ToContent
                        .EndCollection
                    .EndCollection
                .ToTables.ByQuery("[table-level-1]").PopulatingRows.FromTemplate("table-level-1-template")
                    .MapValue(n => n.ShuffledNumber).ToElements.ByQuery("tr > td").ToContent
                    .MapCollection(n => n.Children).ToContainerElements.ByQuery("gfddgfg").FromTemplate("dfdfsdf")
                        .MapValue(c => c.ShuffledNumber).ToElements.ByQuery("dfdsfdf").ToContent
                        .MapCollection(c => c.Children).ToContainerElements.ByQuery("fsdfsdf").FromTemplate("dfdsfdf")
                            .MapValue(c => c.ShuffledNumber).ToElements.ByQuery("dfdsfdf").ToContent
                        .EndCollection
                    .EndCollection
            .EndCollection
            .Data;

    private Task UpdateViewModel(FromTemplateViewModel vm)
    {
        var now = DateTime.Now;
        var shuffledNumbers = ReshuffleNumbers();

        var newVM = new FromTemplateViewModel(now, shuffledNumbers);

        return viewUpdater.Update(newVM);
    }

    private IEnumerable<int> ReshuffleNumbers()
    {
        numbersToSuffle = numbersToSuffle.Shuffle();
        return numbersToSuffle;
    }

    private static string FormatTime(DateTime now)
        => now.ToString("HH:mm:ss");
}
