using Vitraux;

namespace LogActions;

public class LogViewModelConfiguration : IViewModelConfiguration<LogViewModel>
{
    public ConfigurationBehavior ConfigurationBehavior
        => new()
        {
            ActionRegistrationStrategy = ActionRegistrationStrategy.OnlyOnceAtStart,
            QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
            TrackChanges = true,
            AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("test 1")
        };

    public ModelMappingData ConfigureMapping(IModelMapper<LogViewModel> modelMapper)
        => modelMapper
            .MapValue(log => log.Log).ToElements.ById("txtLog").ToContent
            .MapAction(log => log.AddLog()).FromInputs.ById("btnSyncDelegate").On("click")
            .MapActionAsync(log => log.AddLogAsync()).FromInputs.ById("btnAsyncDelegate").On("click")
            .MapAction<SyncBinder>().FromInputs.ById("btnSyncBinder").On("click")
                .AddParameter("numbers").FromParamInputs.ByQuery("input[type='number']")
                .AddParameter("extratext").FromParamInputs.ByQuery("input[type='text']")
            .MapActionAsync<AsyncBinder>().FromInputs.ById("btnAsyncBinder").On("click")
                .AddParameter("numbers").FromParamInputs.ByQuery("input[type='number']")
                .AddParameter("extratext").FromParamInputs.ByQuery("input[type='text']")
            .Data;
}
