using Vitraux.Helpers;

namespace Vitraux.Test.Example;

public class PetOwnerConfiguration(IDataUriConverter dataUriConverter) : IViewModelConfiguration<PetOwner>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        VMAutoGeneratedFunctionCaching = VMAutoGeneratedFunctionCaching.ByVersion("test 1.0")
    };

    public ModelMappingData ConfigureMapping(IModelMapper<PetOwner> modelMapper)
        => modelMapper
            .MapAction(po => po.Method1())
                .FromInputs.ByQuery("el1").On("event1")
            .MapAction(po => po.Method1())
                .FromInputs.ByQuery("el2").On("event2")
                .FromInputs.ByQuery("el3").On("event3", "event4")
            .MapActionAsync((po) => po.Method2())
                .FromInputs.ByQuery("el4").On("event5")
            .MapActionAsync((po) => po.Method2())
                .FromInputs.ByQuery("el5").On("event6", "event7")
                .FromInputs.ById("el6").On("event8", "event9")
            .MapAction<IPetOwnerActionParameterBinder1>()
                .FromInputs.ById("el7").On("event10")
                .AddParameterValue
            .MapActionAsync<IPetOwnerActionParameterBinder2>()
                .FromInputs.ById("el8").On("event11")
                .AddParameterValue
                .AddParameter("p1").FromParamInputs.ByQuery("el9")
                .AddParameter("p2").FromParamElements.ById("el10").FromContent
            .MapActionAsync<PetOwnerActionParameterBinder3>()
                .FromInputs.ById("el11").On("event12")
                .FromInputs.ByQuery("el12").On("event13", "event14")
                .AddParameterValue
            .MapAction<PetOwnerActionParameterBinder4>()
                .FromInputs.ById("el13").On("event15")
                .FromInputs.ByQuery("el14").On("event16", "event17")
                .AddParameterValue
                .AddParameter("p3").FromParamInputs.ById("el15")
                .AddParameter("p4").FromParamElements.ByQuery("el16").FromAttribute("att1")
            .MapValue(po => po.Name)
                .ToElements.ById("petowner-name").ToContent
                .ToJsFunction("poNameFunction").FromModule(new Uri("./modules/po.js", UriKind.Relative))
            .MapValue(po => po.Address)
                .ToElements.ById("petowner-address-parent")
                    .Insert.FromTemplate("petowner-address-template")
                    .ToChildren.ByQuery(".petowner-address-target")
                        .ToContent
                .ToElements.ByQuery(".petwoner-address > div").ToAttribute("data-petowner-address")
            .MapValue(po => po.PhoneNumber)
                .ToElements.ByQuery(".petowner-phonenumber")
                    .Insert.FromUri(new Uri("./htmlpieces/phoneblock.html", UriKind.Relative))
                    .ToChildren.ByQuery(".petowner-phonenumber-target")
                        .ToAttribute("data-phonenumber")
                .ToElements.ById("petowner-phonenumber-id").ToContent
            .MapValue(po => po.Subscription)
                .ToOwnMapping
            .MapValue(po => po.HtmlComments)
                .ToElements.ByQuery(".comments").ToHtml
            .MapCollection(po => po.Pets)
                .ToJsFunction("pets.manage").FromModule(new Uri("./modules/pets.js", UriKind.Relative))
                .ToTables.ById("pets-table")
                .PopulatingRows.FromTemplate("pet-row-template")
                    .MapValue(pet => pet.Name)
                        .ToElements.ByQuery(".cell-pet-name").ToContent
                        .ToElements.ByQuery(".anchor-cell-pet-name").ToAttribute("href")
                        .ToElements.ByQuery(".another-anchor-cell-pet-name").ToAttribute("href")
                    .MapCollection(pet => pet.Vaccines)
                        .ToTables.ByQuery(".inner-table-vaccines")
                            .PopulatingRows.ToTBody(1).FromUri(new Uri("./htmlpieces/row-vaccines.html", UriKind.Relative))
                                .ToOwnMapping
                    .EndCollection
                    .MapValue(pet => ToDataUri(pet.Photo)).ToElements.ByQuery(".pet-photo").ToAttribute("src")
                    .MapCollection(pet => pet.Antiparasitics)
                        .ToJsFunction("globalThis.manageAntiparasitics")
                        .ToContainerElements.ByQuery(".inner-nav-antiparasitics")
                        .FromUri(new Uri("./htmlpieces/row-antiparasitics.html", UriKind.Relative))
                            .MapValue(a => a.Name).ToElements.ByQuery(".div-antiparasitics").ToContent
                            .MapValue(a => a.DateApplied).ToElements.ByQuery(".span-antiparasitics-date").ToContent
                    .EndCollection
            .EndCollection
            .Data;

    private string ToDataUri(byte[] data) => dataUriConverter.ToDataUri(MimeImage.Png, data);
}
