using Vitraux.Helpers;

namespace Vitraux.Test.Example;

public class PetOwnerConfiguration(
    IDataUriConverter dataUriConverter,
    IPetOwnerActionParameterBinder1 parameterBinder1,
    IPetOwnerActionParameterBinder2 parameterBinder2,
    IPetOwnerActionParameterBinder3 parameterBinder3,
    IPetOwnerActionParameterBinder4 parameterBinder4) : IModelConfiguration<PetOwner>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true,
        VMAutoGeneratedFunctionCaching = VMAutoGeneratedFunctionCaching.ByVersion("test 1.0")
    };

    public ModelMappingData ConfigureMapping(IModelMapper<PetOwner> modelMapper)
        => modelMapper
            .MapAction(po => po.Method1())
                .FromInputs.ByQuery("1").On("fdfd")
            .MapAction(po => po.Method1())
                .FromInputs.ByQuery("1").On("fdfd")
                .FromInputs.ByQuery("1").On("fdfsadsd")
            .MapAction((po) => po.Method2())
                .FromInputs.ByQuery("1").On("fdfd")
            .MapAction((po) => po.Method2())
                .FromInputs.ByQuery("1").On("fdfd", "gfg")
                .FromInputs.ById("dfsa").On("ghg","gfg")
            .MapAction(parameterBinder1)
                .FromInputs.ById("2").On("sdfdfr").AddParameterValue
            .MapAction(parameterBinder2)
                .FromInputs.ById("2").On("sdfdfr")
                    .AddParameterValue
                    .AddParameter("dsfdfdsf").FromParamInputs.ByQuery("gfgdfg")
                    .AddParameter("dfsdfsdf").FromParamElements.ById("dfdsf").FromContent
            .MapAction(parameterBinder3)
                .FromInputs.ById("2").On("sdfdfr")
                .FromInputs.ByQuery("ffdfds").On("dfsdff","fdfdfd")
                    .AddParameterValue
            .MapAction(parameterBinder4)
                .FromInputs.ById("2").On("sdfdfr")
                .FromInputs.ByQuery("ffdfds").On("dfsdff", "fdfdfd")
                    .AddParameterValue
                    .AddParameter("dfdsfsdf").FromParamInputs.ById("gfgdfg")
                    .AddParameter("dfsdfsdf").FromParamElements.ByQuery("dfdsf").FromAttribute("dfsdf")
            .MapAction(parameterBinder1)
                .FromInputs.ByQuery("ffdfds").On("dfsdff", "fdfdfd")
                    .AddParameter("dfdsfsdf").FromParamInputs.ById("gfgdfg")
                    .AddParameter("dfsdfsdf").FromParamElements.ByQuery("dfdsf").FromContent
            .MapAction(parameterBinder2)
                .FromInputs.ByQuery("ffdfds").On("dfsdff", "fdfdfd")
                .FromInputs.ById("2").On("sdfdfr")
                    .AddParameter("dfdsfsdf").FromParamInputs.ById("gfgdfg")
                    .AddParameter("dfsdfsdf").FromParamElements.ByQuery("dfdsf").FromAttribute("dfsdf")
            .MapValue(po => po.Name)
                .ToElements.ById("petowner-name").ToContent
                .ToJsFunction("poNameFunction").FromModule(new Uri("./modules/po.js", UriKind.Relative))
            .MapValue(po => po.Address)
                .ToElements.ById("petowner-address-parent")
                    .Insert.FromTemplate("petowner-address-template")
                    .ToChildren.ByQuery(".petowner-address-target")
                        .ToContent
                .ToElements.ByQuery(".petwoner-address > div").ToAttribute("data-petowner-address")
            .MapValue(po => po.PhoneNumber)
                .ToElements.ByQuery(".petowner-phonenumber")
                    .Insert.FromUri(new Uri("./htmlpieces/phoneblock.html", UriKind.Relative))
                    .ToChildren.ByQuery(".petowner-phonenumber-target")
                        .ToAttribute("data-phonenumber")
                .ToElements.ById("petowner-phonenumber-id").ToContent
            .MapValue(po => po.Subscription)
                .ToOwnMapping
            .MapValue(po => po.HtmlComments)
                .ToElements.ByQuery(".comments").ToHtml
            .MapCollection(po => po.Pets)
                .ToJsFunction("pets.manage").FromModule(new Uri("./modules/pets.js", UriKind.Relative))
                .ToTables.ById("pets-table")
                .PopulatingRows.FromTemplate("pet-row-template")
                    .MapValue(pet => pet.Name)
                        .ToElements.ByQuery(".cell-pet-name").ToContent
                        .ToElements.ByQuery(".anchor-cell-pet-name").ToAttribute("href")
                        .ToElements.ByQuery(".another-anchor-cell-pet-name").ToAttribute("href")
                    .MapCollection(pet => pet.Vaccines)
                        .ToTables.ByQuery(".inner-table-vaccines")
                            .PopulatingRows.ToTBody(1).FromUri(new Uri("./htmlpieces/row-vaccines.html", UriKind.Relative))
                                .ToOwnMapping
                    .EndCollection
                    .MapValue(pet => ToDataUri(pet.Photo)).ToElements.ByQuery(".pet-photo").ToAttribute("src")
                    .MapCollection(pet => pet.Antiparasitics)
                        .ToJsFunction("globalThis.manageAntiparasitics")
                        .ToContainerElements.ByQuery(".inner-nav-antiparasitics")
                        .FromUri(new Uri("./htmlpieces/row-antiparasitics.html", UriKind.Relative))
                            .MapValue(a => a.Name).ToElements.ByQuery(".div-antiparasitics").ToContent
                            .MapValue(a => a.DateApplied).ToElements.ByQuery(".span-antiparasitics-date").ToContent
                    .EndCollection
            .EndCollection
            .Data;

    private string ToDataUri(byte[] data) => dataUriConverter.ToDataUri(MimeImage.Png, data);
}
