namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IJsQueryFromTemplateElementsDeclaringOnlyOnceOnDemandGeneratorFactory
    : IJsQueryFromTemplateElementsDeclaringGeneratorFactory
{
}