namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IJsQueryFromTemplateElementsDeclaringOnlyOnceOnDemandGeneratorContext
    : IJsQueryFromTemplateElementsDeclaringGeneratorContext
{
}