namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IJsQueryPopulatingElementsDeclaringOnlyOnceOnDemandGeneratorContext
    : IJsQueryPopulatingElementsDeclaringGeneratorContext
{
}