namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IQueryElementsDeclaringOnlyOnceOnDemandCollectionByUriJsGenerator : IQueryElementsDeclaringJsGenerator
{
}
