namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IQueryElementsDeclaringOnlyOnceOnDemandByQuerySelectorJsCodeGenerator : IQueryElementsDeclaringJsCodeGenerator { }
