namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IQueryElementsDeclaringOnlyOnceOnDemandByIdJsCodeGenerator : IQueryElementsDeclaringJsCodeGenerator { }
