namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IQueryElementsDeclaringOnlyOnceOnDemandByQuerySelectorJsGenerator : IQueryElementsDeclaringJsGenerator { }
