namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OnlyOnceOnDemand;

internal interface IQueryElementsDeclaringOnlyOnceOnDemandCollectionByTemplateJsGenerator : IQueryElementsDeclaringJsGenerator
{
}
