namespace Vitraux;

public abstract record class AutoGeneratedFunctionCaching
{
    public static AutoGeneratedFunctionCaching NoCache { get; } = new AutoGeneratedFunctionNoCache();
    public static AutoGeneratedFunctionCaching ByVersion(string version) => new AutoGeneratedFunctionCacheByVersion(version);
}
