namespace Vitraux;

public abstract record class VMAutoGeneratedFunctionCaching
{
    public static VMAutoGeneratedFunctionCaching NoCache { get; } = new VMAutoGeneratedFunctionNoCache();
    public static VMAutoGeneratedFunctionCaching ByVersion(string version) => new VMAutoGeneratedFunctionCacheByVersion(version);
}
