namespace Vitraux.Execution.Tracking.Encoded;
internal record class EncodedTrackedViewModelJsAllData(IEnumerable<EncodedTrackedJsValueData> ValueProperties, IEnumerable<EncodedTrackedViewModelJsCollectionData> CollectionProperties);
