using Vitraux.Execution.JsInvokers.ViewFunctions;
using Vitraux.Execution.ViewModelNames;
using Vitraux.Helpers;
using Vitraux.JsCodeGeneration;
using Vitraux.JsCodeGeneration.JsObjectNames;

namespace Vitraux.Execution.Building;

internal class ViewModelUpdateFunctionBuilder<TViewModel>(
    IJsFullObjectNamesGenerator jsFullObjectNamesGenerator,
    IRootJsGenerator rootJsGenerator,
    IJsInitializeNonCachedViewFunctionsInvoker jsInitializeNonCachedViewFunctionsInvoker,
    IJsTryInitializeViewFunctionsFromCacheByVersionInvoker jsTryInitializeViewFunctionsFromCacheByVersionInvoker,
    IJsInitializeNewViewFunctionsToCacheByVersionInvoker jsinitializeNewViewFunctionsToCacheByVersionInvoker,
    IViewModelJsNamesMapper encodedSerializationDataMapper,
    IViewModelJsNamesCacheGeneric<TViewModel> vmSerializationDataCache,
    INotImplementedCaseGuard notImplementedCaseGuard)
    : IViewModelUpdateFunctionBuilder<TViewModel>
{
    public Task Build(string vmKey, ConfigurationBehavior configurationBehavior, ModelMappingData modelMappingData)
    {
        var fullObjNames = jsFullObjectNamesGenerator.Generate(modelMappingData);

        StoreSerializationData(vmKey, fullObjNames);

        return configurationBehavior.VMAutoGeneratedFunctionCaching switch
        {
            VMAutoGeneratedFunctionNoCache => InvokeInitializationViewFunctionsNoCache(vmKey, fullObjNames, configurationBehavior.QueryElementStrategy),
            VMAutoGeneratedFunctionCacheByVersion cacheByVersion => InvokeInitializationViewFunctionsByVersion(vmKey, cacheByVersion.Version, fullObjNames, configurationBehavior.QueryElementStrategy),
            _ => notImplementedCaseGuard.ThrowException<Task>(configurationBehavior.VMAutoGeneratedFunctionCaching)
        };
    }

    private void StoreSerializationData(string vmKey, FullObjectNames fullObjectNames)
    {
        vmSerializationDataCache.ViewModelKey = vmKey;
        vmSerializationDataCache.ViewModelJsNames = encodedSerializationDataMapper.MapFromFull(fullObjectNames);
    }

    private GeneratedJsCode GenerateJsCode(FullObjectNames fullObjectNames, QueryElementStrategy queryElementStrategy)
        => rootJsGenerator.GenerateJs(fullObjectNames, queryElementStrategy);

    private async Task InvokeInitializationViewFunctionsByVersion(string vmKey, string version, FullObjectNames fullObjectNames, QueryElementStrategy queryElementStrategy)
    {
        if (!await jsTryInitializeViewFunctionsFromCacheByVersionInvoker.Invoke(vmKey, version))
        {
            var generatedJsCode = GenerateJsCode(fullObjectNames, queryElementStrategy);
            await jsinitializeNewViewFunctionsToCacheByVersionInvoker.Invoke(vmKey, version, generatedJsCode.InitializeViewJs, generatedJsCode.UpdateViewJs);
        }
    }

    private Task InvokeInitializationViewFunctionsNoCache(string vmKey, FullObjectNames fullObjectNames, QueryElementStrategy queryElementStrategy)
    {
        var generatedJsCode = GenerateJsCode(fullObjectNames, queryElementStrategy);
        return jsInitializeNonCachedViewFunctionsInvoker.Invoke(vmKey, generatedJsCode.InitializeViewJs, generatedJsCode.UpdateViewJs);
    }
}
