using Vitraux.Execution.JsInvokers.Actions.Registration;
using Vitraux.Helpers;
using Vitraux.JsCodeGeneration.Actions;
using Vitraux.JsCodeGeneration.JsObjectNames;
using Vitraux.Modeling.Data.Actions;

namespace Vitraux.Execution.Building;

internal class ViewModelActionsBuilder<TViewModel>(
    IJsActionElementObjectNamesGenerator jsActionElementObjectNamesGenerator,
    IRootActionsJsGenerator rootActionsJsGenerator,
    IJsTryInitializeActionsFunctionFromCacheByVersionInvoker tryInitializeFromCacheByVersionInvoker,
    IJsInitializeNewActionsFunctionToCacheByVersionInvoker initializeNewToCacheByVersionInvoker,
    IJsInitializeNonCachedActionsFunctionInvoker initializeNonCachedInvoker,
    INotImplementedCaseGuard notImplementedCaseGuard) : IViewModelActionsBuilder<TViewModel>
{
    public Task Build(string vmKey, ConfigurationBehavior configurationBehavior, IEnumerable<ActionData> actions)
    {
        switch (configurationBehavior.VMAutoGeneratedFunctionCaching)
        {
            case VMAutoGeneratedFunctionNoCache:
                InvokeInitializationNonCache(vmKey, configurationBehavior.QueryElementStrategy, configurationBehavior.ActionRegistrationStrategy, actions);
                break;

            case VMAutoGeneratedFunctionCacheByVersion cacheByVersion:
                InvokeInitializationByVersion(vmKey, cacheByVersion.Version, configurationBehavior.QueryElementStrategy, configurationBehavior.ActionRegistrationStrategy, actions);
                break;

            default:
                notImplementedCaseGuard.ThrowException(configurationBehavior.VMAutoGeneratedFunctionCaching);
                break;
        }

        return Task.CompletedTask;
    }

    private string GenerateJsCode(string vmKey, QueryElementStrategy queryElementStrategy, IEnumerable<ActionData> actions)
    {
        var jsNames = jsActionElementObjectNamesGenerator.Generate(string.Empty, actions);
        return rootActionsJsGenerator.GenerateJs(vmKey, actions, jsNames, queryElementStrategy);
    }

    private void InvokeInitializationByVersion(string vmKey, string version, QueryElementStrategy queryElementStrategy, ActionRegistrationStrategy actionRegistrationStrategy, IEnumerable<ActionData> actions)
    {
        if (!tryInitializeFromCacheByVersionInvoker.Invoke(vmKey, version))
        {
            var generatedJsCode = GenerateJsCode(vmKey, queryElementStrategy, actions);
            initializeNewToCacheByVersionInvoker.Invoke(vmKey, version, generatedJsCode, actionRegistrationStrategy);
        }
    }

    private void InvokeInitializationNonCache(string vmKey, QueryElementStrategy queryElementStrategy, ActionRegistrationStrategy actionRegistrationStrategy, IEnumerable<ActionData> actions)
    {
        var generatedJsCode = GenerateJsCode(vmKey, queryElementStrategy, actions);
        initializeNonCachedInvoker.Invoke(vmKey, generatedJsCode, actionRegistrationStrategy);
    }
}